import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/Header";
import { ClerkProvider } from "@clerk/nextjs";


export const metadata: Metadata = {
  title: "EndPoints",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider>
    <html lang="en">
      <body className="">
        <div className="max-w-6xl mx-auto px-2">
        <Header />
        {children}
        </div>
        </body>
    </html>
    </ClerkProvider>

  );
}
